# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: CravateRouge Ltd # Website name
baseURL: 'https://cravaterouge.com/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  - target:
      path: "/articles/**"
      kind: page
    announcement: true
    show_related: true
    show_date_updated: true
    commentable: true
    pager: true
    editable: true
  - target:
      path: "{/reference,/reference/**,/authors,/authors/**,/services}"
    _build:
      render: never
  - target:
      path: "{/privacy,/terms,/services/**}"
    share: false
    reading_time: false
    show_related: false
    show_date: false
    show_date_updated: false
    show_breadcrumb: false
    commentable: false
    pager: false
    profile: false
  - target:
      path: "{/privacy,/terms}"
    private: true
  - target:
      path: "/articles/*"
      kind: section
    # Set the listing view
    view: date-title-summary

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: false
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 95
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
