# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

i_am_a_sponsor: true
power_ups:
  hide_published_with: true
  
# Appearance
appearance:
  mode: light
  color: red

# SEO
marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: 'ProfessionalService'
    org_name: ''
    description: |
      Keep it tight with your security. At CravateRouge Ltd we provide cybersecurity services tailored to your needs.
      From protection to audit, we also provide trainings, forensic and custom security softwares.
    twitter: 'rouge_cravate'
  analytics:
    google_analytics: 'G-64YDD5310R'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Contact Us"
      url: "contact/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: |
      © {year} CravateRouge Ltd. All rights reserved.\
      CravateRouge Limited is a private limited company registered in Hong Kong SAR under the incorporation number 76292843.

# Localization
locale:
  date_format: '2 Jan, 2006'
  time_format: '15:04'